Header header
float64 ec_max # [J]
float64 ec_pred # [J]
float64 ec_consumed # [J]
uint64 energy_condition 
float64 t_traj_curr 
float64 m_u # [Kg]
float64 vmax_ec # [m/s]
float64 human_workspace_distance # [m]
geometry_msgs/Pose X_curr
geometry_msgs/Pose X_traj
geometry_msgs/Pose X_fake_human
geometry_msgs/Twist Xd_traj
geometry_msgs/Twist Xdd_traj
geometry_msgs/Twist X_err
geometry_msgs/Twist Xd_control
